#ifndef OPENOMF_GAME_COMMONDEFINES_HPP
#define OPENOMF_GAME_COMMONDEFINES_HPP

namespace openomf {
namespace game {

/** C game/common_defines.h scene id enum. */
enum SceneId {
    SCENE_NONE = 0,
    SCENE_INTRO,
    SCENE_OPENOMF,
    SCENE_MENU,
    SCENE_END,
    SCENE_END1,
    SCENE_END2,
    SCENE_CREDITS,
    SCENE_MECHLAB,
    SCENE_VS,
    SCENE_MELEE,
    SCENE_NEWSROOM,
    SCENE_ARENA0,
    SCENE_ARENA1,
    SCENE_ARENA2,
    SCENE_ARENA3,
    SCENE_ARENA4,
    SCENE_TRN_CUTSCENE,
    SCENE_SCOREBOARD,
    SCENE_LOBBY,
    NUMBER_OF_SCENE_TYPES,
};

enum AIDifficulty {
    AI_DIFFICULTY_PUNCHING_BAG = 0,
    AI_DIFFICULTY_ROOKIE,
    AI_DIFFICULTY_VETERAN,
    AI_DIFFICULTY_WORLD_CLASS,
    AI_DIFFICULTY_CHAMPION,
    AI_DIFFICULTY_DEADLY,
    AI_DIFFICULTY_ULTIMATE,
    NUMBER_OF_AI_DIFFICULTY_TYPES,
};

enum HarId {
    HAR_JAGUAR = 0,
    HAR_SHADOW,
    HAR_THORN,
    HAR_PYROS,
    HAR_ELECTRA,
    HAR_KATANA,
    HAR_SHREDDER,
    HAR_FLAIL,
    HAR_GARGOYLE,
    HAR_CHRONOS,
    HAR_NOVA,
    NUMBER_OF_HAR_TYPES,
};

enum PilotId {
    PILOT_CRYSTAL = 0,
    PILOT_STEFFAN,
    PILOT_MILANO,
    PILOT_CHRISTIAN,
    PILOT_SHIRRO,
    PILOT_JEANPAUL,
    PILOT_IBRAHIM,
    PILOT_ANGEL,
    PILOT_COSSETTE,
    PILOT_RAVEN,
    PILOT_KREISSACK,
    NUMBER_OF_PILOT_TYPES,
    NUMBER_OF_PLAYABLE_PILOT_TYPES = NUMBER_OF_PILOT_TYPES - 1,
};

enum RoundType {
    ROUND_TYPE_ONE = 0,
    ROUND_TYPE_2_OF_3,
    ROUND_TYPE_3_OF_5,
    ROUND_TYPE_4_OF_7,
    NUMBER_OF_ROUND_TYPES,
};

enum PilotSex {
    PILOT_SEX_MALE,
    PILOT_SEX_FEMALE,
};

inline bool is_valid_scene(unsigned int id) {
    return id < static_cast<unsigned int>(NUMBER_OF_SCENE_TYPES);
}

} // namespace game
} // namespace openomf

#endif // OPENOMF_GAME_COMMONDEFINES_HPP
